# INFO ENDPOINT CONFIGURATION

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@
# Spring Security Default user name and password
spring:
  application:
    name: actuator1
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR_ADMIN
management:
  metrics:
    tags:
      application: ${spring.application.name}
      region: region1
    export:
      jmx:
        domain: com.summer.metrics
      newrelic:
        account-id: 2357933
        api-key: 6fa32be9f12b14a3a9a60b699599dec8
        step: 1m
        enabled: false
      kairos:
        enabled: false
        step: 1m
        user-name: ly1989124423@163.com
        password: qq1989124423
  health:
    status:
      order: FATAL, DOWN, OUT_OF_SERVICE, UNKNOWN, UP
      http-mapping:
        FATAL:
          503
  info:
    git:
      mode: simple # simple full
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      # include: health,info,auditevents,beans,caches,conditions,configprops,env,httptrace,integrationgraph,loggers,liquibase,metrics,mappings,scheduledtasks,sessions,threaddump,shutdown,heapdump,jolokia,logfile,prometheus
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always
    auditevents:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    loggers:
      enabled: true
    logfile:
      enabled: true
    httptrace:
      enabled: true
    env:
      enabled: true
    flyway:
      enabled: true
    liquibase:
      enabled: true
    shutdown:
      enabled: true
    mappings:
      enabled: true
    scheduledtasks:
      enabled: true
    threaddump:
      enabled: true
    heapdump:
      enabled: true