# INFO ENDPOINT CONFIGURATION
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@
# Spring Security Default user name and password
spring:
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR_ADMIN
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: health,info,auditevents,beans,caches,conditions,configprops,env,httptrace,integrationgraph,loggers,liquibase,metrics,mappings,scheduledtasks,sessions,threaddump,shutdown,heapdump,jolokia,logfile,prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    auditevents:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    loggers:
      enabled: true
    logfile:
      enabled: true
    httptrace:
      enabled: true
    env:
      enabled: true
    flyway:
      enabled: true
    liquibase:
      enabled: true
    shutdown:
      enabled: true
    mappings:
      enabled: true
    scheduledtasks:
      enabled: true
    threaddump:
      enabled: true
    heapdump:
      enabled: true