server:
  port: 8001
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: false
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 80
        max-size:  200
        queue-capacity: 400
      thread-name-prefix: AsyncTaskExecutor-

#    pool:
#      max-connections: 100
#      idle-timeout: 30s
#      enabled: true