server:
  port: 8001
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      max-connections: 30
      idle-timeout: 30s
      enabled: true